name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Remplacez par la branche sur laquelle vous souhaitez déployer

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install # Assurez-vous que ViteJS est installé ici si nécessaire

      - name: Build project
        run: npm run build # Commande pour construire votre projet ViteJS

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Répertoire où se trouvent les fichiers à déployer

